### ISSUE TITLE
v2.4.0-MOD_1.3 does not work with OnePlus6T/LineageOS-microG, while v2.3.1-MOD_3.0 worked

### ISSUE THREAD

**Issue by alpianon** [Displax/safetynet-fix#12]
**Describe the bug**
v2.3.1-MOD_3.0 works on an OnePlus 6T with LineageOS 20, next versions do not work

**To reproduce**

- OnePlus 6T
- LineageOS 20-20230704-microG-fajita
- Magisk 26.1 with zygisk enabled + MagiskHide Props Config 6.1.2-v137
- device fingerprint set to OnePlus6T:11
- if I install  safetynet-fix v2.3.1-MOD_3.0 all checks pass (with BASIC auth, even if I didn't force it via props)
- If I install latest version I get "Basic Integrity" and "CTS Profile does not match" errors (it tries HARDWARE_BACKED, even if I force BASIC auth via props)
- if I reinstall  v2.3.1-MOD_3.0 all checks pass again

**Expected behavior**
Also latest version works

**Screenshots of SafetyNet & Play Integrity API tests result**

Testing SafetyNet: 

<table><tr>
<th>Screenshot_YASNAC_failure_with_v2.4.0-MOD_1 3</th>
<th>Screenshot_YASNAC_success_with_v2.3.1-MOD_3 0</th>
</tr>
<tr>
<td>
<img src=https://github.com/Displax/safetynet-fix/assets/3025020/5dbe63fb-b967-4a6e-9d62-9f0a55a23706>
</td>
<td>
<img src=https://github.com/Displax/safetynet-fix/assets/3025020/97af7918-51a1-47bc-82ec-a8080f9ce207>
</td>
</tr>
</table>

Testing Play Integrity API: I don't have Google Play store installed

**Device info**
Device model: OnePlus 6T
Android version: 13
ROM name/version: LineageOS 20-20230704-microG-fajita

**Logs**

[issue.log](https://github.com/Displax/safetynet-fix/files/12078946/issue.log)

**Additional context**

n/a

**Checklist**
- [x] I confirm that the SELinux status is `Enforcing` on my device.
- [x] All information is present
- [x] Screenshots are attached
- [x] Logs are attached

**Comment by Displax** [comment]
Use version 1.3-microG
