### ISSUE TITLE
Se linux flag issue

### ISSUE THREAD

**Issue by rehannali** [Displax/safetynet-fix#15]
**Describe the bug**
- All check are passed except selinux flag. 

**To reproduce**
1. Got to rootbear sample app GitHub
2. Install app
3. Check status for root.
4. Shows se linux flag enable. Root detected. 

**Expected behavior**
It should pass all test

**Screenshots of SafetyNet & Play Integrity API tests result**
Testing SafetyNet: https://play.google.com/store/apps/details?id=rikka.safetynetchecker
Testing Play Integrity API: https://play.google.com/store/apps/details?id=gr.nikolasspyr.integritycheck

**Device info**
Device model: S21 Ultra
Android version: 13
ROM name/version: Stock

**Checklist**
- [x] I confirm that the SELinux status is `Enforcing` on my device.
- [x] All information is present

**Comment by RameshGokamalla** [comment]
Still Google Play Store is uncertified.

**Comment by rehannali** [comment]
Yes, it is not certified.
