### ISSUE TITLE
MicroG issue, once again

### ISSUE THREAD

**Issue by j0110** [Displax/safetynet-fix#16]
New version isn't working with MicroG.
Both from standard and STRONG build.
![Screenshot_20230721-164016_Yet Another SafetyNet Attestation Checker](https://github.com/Displax/safetynet-fix/assets/23175256/98b38222-bc76-480a-ace3-c8ac8749fa8b)

**Comment by Displax** [comment]
Expected. Use old one 1.3

**Comment by j0110** [comment]
Can't you manage to port it to microg as you incredibly did for 1.3 ?
