### ISSUE TITLE
MEET_STRONG_INTEGRITY not passed

### ISSUE THREAD

**Issue by King-Of-Knights** [Displax/safetynet-fix#20]
**Describe the bug**
Hi there, MEET_STRONG_INTEGRITY is fail while MEET_BASIC_INTEGRITY and MEET_DEVICE_INTEGRITY both pass. 

**Expected behavior**
MEET_STRONG_INTEGRITY pass

**Screenshots of SafetyNet & Play Integrity API tests result**
[Testing SafetyNet](https://imgse.com/i/pCxVDUI)
[Testing Play Integrity API](https://imgse.com/i/pCxVfbj)

**Device info**
Device model: Redmi k50 ultra/ Xiaomi 12T Pro (diting) 
Android version: 13
ROM name/version: V14.0.10.0.TLFCNXM

**Additional context**
Since I saw you have said MEET_STRONG_INTEGRITY has been fixed in last week Release. I think I should pass MEET_STRONG_INTEGRITY as well? Thanks for your work!

**Checklist**
- [√] I confirm that the SELinux status is `Enforcing` on my device.
- [√] All information is present
- [√] Screenshots are attached

**Comment by personshelldon** [comment]
Ig You want to pass STRONG_INTEGRITY, just unroot Your device and lock it. It mostly never work with unlocked bootloader.

**Comment by King-Of-Knights** [comment]
@personshelldon Hi, thanks for the response! I saw the lastest release [log](https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_2.0), looks like the author has already settled STRONG_INTEGRITY. Maybe I am misunderstood?

**Comment by Displax** [comment]
Please read release notes carefully. Your ro.product.first_api_level must be 33 or null or not present.

**Comment by King-Of-Knights** [comment]
@Displax Sorry to bother again, I change another device, Xiaomi Pad 6Pro, which is Android 13 and ro.product.first_api_level 33, magisk 26.1, but still not pass ([result](https://imgse.com/i/pPpbBOf)), any idea?

**Comment by Displax** [comment]
> @Displax Sorry to bother again, I change another device, Xiaomi Pad 6Pro, which is Android 13 and ro.product.first_api_level 33, magisk 26.1, but still not pass ([result](https://imgse.com/i/pPpbBOf)), any idea?

Google fixed this.

**Comment by King-Of-Knights** [comment]
@Displax Oh~, sorry to hear that T_T, anyway, Thanks for your great contribution!
