### ISSUE TITLE
No strong integrity anymore after newes OnePlus 10 Pro update

### ISSUE THREAD

**Issue by Tragen** [Displax/safetynet-fix#26]
Before the update, when I used the STRONG version 2.4.0 MOD 2.0, I had Device Integrity and Strong Integrity green.
Now after the update, only Basic Integrity is green. When I use the normal version and not the STRONG version, I have Device and Basic Integrity green but not strong integrity.

**Comment by personshelldon** [comment]
> Before the update,

Someone here said STRONG integrity is not working anymore after the latest Google Security patches update. Goolge fixed that check.

**Comment by Tragen** [comment]
I had all updates from Google installed and it was working for me. So I thought it's the update from OnePlus

**Comment by personshelldon** [comment]
Of course, Google security patches are integrated into a system update, not in apps updates. The only thing that You can do now - is revert the system version to the previous one.

**Comment by Tragen** [comment]
Okay, I thought it has something to do with the Play integrity services that are always updated without full system updates.

**Comment by personshelldon** [comment]
> Okay, I thought it has something to do with the Play integrity services that are always updated without full system updates.

Can I ask You: I also have the OnePlus 10 pro with the latest system update. Does  2.4.0 MOD 2.0 work correctly for You (for me most important is GPay)? I am not updating because I do not want to lose GPay support and I am now on version 2.4.0 MOD 1.2. No Strong integrity but GPay works.

**Comment by Tragen** [comment]
I've just updated so I don't know. I can open the wallet without errors.

**Comment by personshelldon** [comment]
> I've just updated so I don't know. I can open the wallet without errors.

Understood. You need to try to pay to check that out. After the first pay, GPay may say that Your device is rooted.

**Comment by Tragen** [comment]
I will test it tomorrow and report

**Comment by Tragen** [comment]
I was in the supermarket and it worked.
Since the update I have the new Wallet where you can see the labels. Before the update it changed daily between the new and the old wallet style.

**Comment by Hot12345** [comment]
So which version do you use to make it work?

**Comment by HarriBuh** [comment]
So, for my understanding: Safetynet-fix's version will always have to catch up to the latest security patch from Google to work?

I'm on A13 on Pixel 7 and am unable to reach strong integrity since Google's latest security update (August) as well.

**Comment by kouzelnik3** [comment]
I am paying without any issues on my 10 pro with that normal 2.0 mod version. :)
