### ISSUE TITLE
microG support

### ISSUE THREAD

**Issue by j0110** [Displax/safetynet-fix#5]
Hey there,
Thanks for your work!
I found that latest release (2.4.0-MOD1.3) fails to pass safety net (both CTS and basic integrity) while version 2.3.1-MOD3.0 do successfully the job.
Is there any particular reason?
Thanks !

**Comment by Undisputed00x** [comment]
Same here! I use a Poco x3 Pro with LineageOS 19.1 (Android 12L) latest build and only 2.3.1-MOD3.0 works for me. Have tried all releases but no success.

**Comment by ghost** [comment]
![GIF-230619_144356](https://github.com/Displax/safetynet-fix/assets/59386233/ce33f95d-73bb-427a-9a9f-8ee169434715)
Same here , Not working with latest module or any module except with 2.3.1-Mod-3.0

**Comment by Displax** [comment]
> 
> ![GIF-230619_144356](https://github.com/Displax/safetynet-fix/assets/59386233/ce33f95d-73bb-427a-9a9f-8ee169434715)
> Same here , Not working with latest module or any module except with 2.3.1-Mod-3.0
> 

Do not use microg

**Comment by Displax** [comment]
@j0110
@AndiDink00x
Do you also use microg?

**Comment by j0110** [comment]
Yes, it is a problem?

**Comment by Displax** [comment]
> Yes, it is a problem?

Yep, use normal GMS.

**Comment by Undisputed00x** [comment]
@Displax im using microg , the question is why does work with gms and not with microg ?

**Comment by Displax** [comment]
@j0110
@AndiDink00x

Yes, that is the problem. Just use normal GMS.
Anyway, could you send your logcat during trying SN/PI tests with latest MOD and `getprop` command?

**Comment by Undisputed00x** [comment]
@Displax 
using latest release

[myprops.txt](https://github.com/Displax/safetynet-fix/files/11794191/myprops.txt)
[mylogcat.txt](https://github.com/Displax/safetynet-fix/files/11794192/mylogcat.txt)

**Comment by Displax** [comment]
@AndiDink00x 
Do not use termux for log, use adb or separate programs to grab logcat.

**Comment by Undisputed00x** [comment]
@Displax 

[myNewProps.txt](https://github.com/Displax/safetynet-fix/files/11800663/myNewProps.txt)
[myNewLogcat.txt](https://github.com/Displax/safetynet-fix/files/11800664/myNewLogcat.txt)

**Comment by Displax** [comment]
Can you confirm that [v2.3.1-MOD_3.0](https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_3.0) works good?
And please test if [v2.3.1-MOD_2.1](https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.1) work/not work?
@AndiDink00x
@j0110

**Comment by j0110** [comment]
Yes, both work.

**Comment by AndiDink00x** [comment]
@Displax  just tested https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_2.1 and i can confirm that too

**Comment by Undisputed00x** [comment]
@Displax yeah both versions work for me also

**Comment by Displax** [comment]
@AndiDink00x
@j0110

Try this build
[safetynet-fix-v2.4.0-MOD_1.2-microG-test.zip](https://github.com/Displax/safetynet-fix/files/11805856/safetynet-fix-v2.4.0-MOD_1.2-microG-test.zip)

**Comment by Displax** [comment]
@AndiDink00x
@j0110

Try this build
[safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip](https://github.com/Displax/safetynet-fix/files/11805865/safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip)

**Comment by j0110** [comment]
It works !

**Comment by Undisputed00x** [comment]
> @AndiDink00x @j0110
> 
> Try this build [safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip](https://github.com/Displax/safetynet-fix/files/11805865/safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip)

@Displax  Yeah it works !!! 

**EDIT** : Microg SN fails (integrity check failed) but YASNAC test passes ... also after some quick retries YASNAC crashes.
**EDIT (2)** : it seems that it is not stable , in SN history in microg shows that also YASNAC fails after couple retries thats why it crashes

**Comment by j0110** [comment]
OK, same for me in fact

**Comment by Undisputed00x** [comment]
@Displax 


![output](https://github.com/Displax/safetynet-fix/assets/80290008/5b5f454b-925e-4d35-a3b6-88c282ed7a4d)

**Comment by Displax** [comment]
@AndiDink00x
@j0110

So, same problem not happens on [v2.3.1-MOD_3.0](https://github.com/Displax/safetynet-fix/releases/tag/v2.3.1-MOD_3.0) ?

**Comment by Undisputed00x** [comment]
@Displax its stable on 2.3.1-MOD_3.0

**Comment by Displax** [comment]
@AndiDink00x
@j0110

Try this 
[safetynet-fix-v2.4.0-MOD_1.3-microG-test2.zip](https://github.com/Displax/safetynet-fix/files/11827336/safetynet-fix-v2.4.0-MOD_1.3-microG-test2.zip)

**Comment by j0110** [comment]
![Screenshot_20230622-113659_Yet Another SafetyNet Attestation Checker](https://github.com/Displax/safetynet-fix/assets/23175256/0e28052b-788b-428d-b1e2-534b749d03ed)
![Screenshot_20230622-113725_microG Services Core](https://github.com/Displax/safetynet-fix/assets/23175256/009f6fad-a8c0-4a03-98df-410d0e5ab8f8)
![Screenshot_20230622-113735_microG Services Core](https://github.com/Displax/safetynet-fix/assets/23175256/faa3436f-1cd0-4d15-b351-bf57644434ba)
Strange... We just got basic integrity and after 2-3 tries it crashes as before...

**Comment by Undisputed00x** [comment]
> @AndiDink00x @j0110
> 
> Try this [safetynet-fix-v2.4.0-MOD_1.3-microG-test2.zip](https://github.com/Displax/safetynet-fix/files/11827336/safetynet-fix-v2.4.0-MOD_1.3-microG-test2.zip)

@Displax 



![output](https://github.com/Displax/safetynet-fix/assets/80290008/f7500450-1b9b-4a8c-8dc6-d8483ae055d3)

**Comment by Displax** [comment]
@AndiDink00x
@j0110

New build 
[safetynet-fix-v2.4.0-MOD_1.3-microG.zip](https://github.com/Displax/safetynet-fix/files/11839311/safetynet-fix-v2.4.0-MOD_1.3-microG.zip)

**Comment by j0110** [comment]
> > @AndiDink00x @j0110
> > Try this build [safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip](https://github.com/Displax/safetynet-fix/files/11805865/safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip)
> 
> @Displax Yeah it works !!!
> 
> **EDIT** : Microg SN fails (integrity check failed) but YASNAC test passes ... also after some quick retries YASNAC crashes. **EDIT (2)** : it seems that it is not stable , in SN history in microg shows that also YASNAC fails after couple retries thats why it crashes

Same as this, for the new build.

**Comment by Displax** [comment]
> Same as this, for the new build.

Too strange... Can you send your `getprop` when my original MOD-3.0 installed, than disable/delete it - reboot, and save `getprop` once again. Thanks.

**Comment by Undisputed00x** [comment]
@Displax 
ok i dunno what is happening, with 2.3.1-mod3.0 now after 2 tries it leads to "integrity check failed" , same as the 2.4.0-microg
these are the props

[myprops-2.3.1_MOD_3.0.txt](https://github.com/Displax/safetynet-fix/files/11840272/myprops-2.3.1_MOD_3.0.txt)

[myprops-2.4.0_MOD_1.3-microG.txt](https://github.com/Displax/safetynet-fix/files/11840273/myprops-2.4.0_MOD_1.3-microG.txt)

**Comment by Undisputed00x** [comment]
[mylogcat-2.4.0_microG.txt](https://github.com/Displax/safetynet-fix/files/11840294/mylogcat-2.4.0_microG.txt)

**Comment by Displax** [comment]
> ok i dunno what is happening, with 2.3.1-mod3.0 now after 2 tries it leads to "integrity check failed" , same as the 2.4.0-microg
> these are the props

So it completely same behavior of this versions. I think microG has "wait timeout" for requests.
Please test on this build [safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip](https://github.com/Displax/safetynet-fix/files/11805865/safetynet-fix-v2.4.0-MOD_1.3-microG-test.zip) `but do not send SN requests very often`.
Just run several test (at least 10 times) `at 5 min.` intervals.

@AndiDink00x
@j0110

**Comment by Undisputed00x** [comment]
@Displax 
After some testing i found out that there is no "timeout", both in microG and YSN there are only 2 available passes after that they fail, **but** if microG is closed/reopened the available successful SN passes are refreshed.
 
For example: opened YASNAC tried 2 times successfully , 3rd time fails-crashes(YASNAC crashes only on "integrity check fail") , closed the app on backround, just launched microG and closed it, then reopened YASNAC and again passed only 2 times.
That happens with also microG.

**Comment by anonimou0** [comment]
Hey. I didn't want to hijack the thread but I didn't find any contact info from you @AndiDink00x .

I also have a Poco x3 Pro but I am one step back. I still can't get SafetyNet to pass (I am using microG).

Do you have any directions or instructions that you could share?

EDIT:
Steps I have taken:
1) I have microG (crDroid), with signature spoofing and Magisk
2) Enabled Zygisk, rebooted
3) Enforced DenyList, rebooted
4) Added to DenyList: microG Services Core (all 4 activities? - unstable, persistent ui), microG Framework Proxy and YASNAC
5) Installed Universal SafetyNet Fix and MagiskHide Props Config, rebooted
5.1 - No props for X3 Pro. Didn't actually do anything
6) Enabled in microG device Google Device Registration, Cloud Messaging and Google SafetyNet
7) Tried to pass SafetyNet attestation.
8) Results: Basic integrity pass. CTS profile match fails.

**Comment by Undisputed00x** [comment]
@anonimou0  user:Undisputed00x on discord

**Comment by Displax** [comment]
@AndiDink00x 
So there is other restriction. Please send logcat from crashes. I don't think it's my module's "problem".
Anyway there is no need to check SN status more than twice in a row. No such app do this, so no real problem on it.

**Comment by Undisputed00x** [comment]
@Displax 
[hereismynewlogcatbud.txt](https://github.com/Displax/safetynet-fix/files/11852857/hereismynewlogcatbud.txt)

**Comment by Displax** [comment]
@AndiDink00x 
Try this, not sure if it fix "problem", but anyway...
[safetynet-fix-v2.4.0-MOD_1.3-microG-unload.zip](https://github.com/Displax/safetynet-fix/files/11853272/safetynet-fix-v2.4.0-MOD_1.3-microG-unload.zip)

**Comment by Undisputed00x** [comment]
@Displax 
same thing ...

**Comment by Displax** [comment]
Ok. So I release microG version "as is" because this behavior should not affect applications in real life. Just do not run attest more than twice in one session.
https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3

**Comment by Void-025** [comment]
Did anyone end up managing to pass the safetynet attestation completely on microg? If so, what steps should I take to get it to work? The best I ever get is "CTS Profile does not match"...

**Comment by personshelldon** [comment]
> Did anyone end up managing to pass the safetynet attestation completely on microg? If so, what steps should I take to get it to work? The best I ever get is "CTS Profile does not match"...

**Comment by personshelldon** [comment]
> Did anyone end up managing to pass the safetynet attestation completely on microg? If so, what steps should I take to get it to work? The best I ever get is "CTS Profile does not match"...

Just use verison 2.3.0. I am using it now and everything work ok with it including microg

**Comment by Void-025** [comment]
> Just use verison 2.3.0. I am using it now and everything work ok with it including microg

Wait, so I shouldn't use the latest version? Even though the latest version has (and is the only version to have) a MicroG-specific release? Also, There's no 2.3.0 version of the mod, do you mean 2.3.1 or should I not even use the mod?

**Comment by personshelldon** [comment]
> > Just use verison 2.3.0. I am using it now and everything work ok with it including microg
> 
> Wait, so I shouldn't use the latest version? Even though the latest version has (and is the only version to have) a MicroG-specific release? Also, There's no 2.3.0 version of the mod, do you mean 2.3.1 or should I not even use the mod?

Sorry, I was incorrect in version. I am using 2.4.0-1.2 now. And everything work.

**Comment by Void-025** [comment]
> Sorry, I was incorrect in version. I am using 2.4.0-1.2 now. And everything work.

I see, but how come the previous version works and the current one, supposedly made specifically for MicroG, doesn't? Shouldn't this issue be re-opened in that case?

**Comment by Undisputed00x** [comment]
@Void-0000 if it works why open the issue

**Comment by Void-025** [comment]
> if it works why open the issue

Apparently, the latest version (1.3) _doesn't_ work, while the previous one (1.2) does. Unless I've missed some part of the process to make it work, this seems like a bit of a problem.
Did you manage to get the latest version working with MicroG?
