### ISSUE TITLE
Riru Version Please 

### ISSUE THREAD

**Issue by VisionR1** [Displax/safetynet-fix#7]
Hi, the new version, it will be only zygisk? or will be and for riru etc? because i have Magisk Delta with magiskhide and riru, because of this written by @HuskyDG

![IMG_20230619_150828](https://github.com/Displax/safetynet-fix/assets/25982450/2f5db7ab-a2c0-4c19-b1c3-abae1878c283)

**Comment by Displax** [comment]
Riru version added.
https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3

**Comment by VisionR1** [comment]
> Riru version added. https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3

Thanks, really can have it indepented install module? like LSposed, when zygisk is enabled the riru module suspended and the reverse, without install it and replacement

![Στιγμιότυπο οθόνης (486)](https://github.com/Displax/safetynet-fix/assets/25982450/53fec009-aff6-4d0d-9beb-e5cef5120131)

**Comment by Displax** [comment]
> > Riru version added. https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3
> 
> Thanks, really can have it indepented install module? like LSposed, when zygisk is enabled the riru module suspended and the reverse, without install it and replacement
> 
> ![Στιγμιότυπο οθόνης (486)](https://github.com/Displax/safetynet-fix/assets/25982450/53fec009-aff6-4d0d-9beb-e5cef5120131)
> 

Just use it with riru. And disable zygisk.

**Comment by VisionR1** [comment]
> > > Riru version added. https://github.com/Displax/safetynet-fix/releases/tag/v2.4.0-MOD_1.3
> > 
> > 
> > Thanks, really can have it indepented install module? like LSposed, when zygisk is enabled the riru module suspended and the reverse, without install it and replacement
> > ![Στιγμιότυπο οθόνης (486)](https://user-images.githubusercontent.com/25982450/248469282-53fec009-aff6-4d0d-9beb-e5cef5120131.png)
> 
> Just use it with riru. And disable zygisk.

Sure, Thanks again for the riru version, keep the good work
