### ISSUE TITLE
Nexus 6P - As of now

### ISSUE THREAD

**Issue by sdfgsdfgd** [Displax/safetynet-fix#9]
**Describe the bug**
Hellooo, nothing works except for Basic Attestation & Basic Integrity + CTS Profile. 
I thought we would be able to at least attain Device Integrity and Strong Attestation, is this not possible ? 

**Expected behavior**
I was expecting to pass Device Integrity and Strong Integrity - but I got s**t instead ?  

Google Pay also doesn't work 
<img width="358" alt="Screenshot 2023-06-22 at 2 51 21 pm" src="https://github.com/Displax/safetynet-fix/assets/16299826/741835c3-32dd-4d34-bbb4-7cc26ed56b70">

**Screenshots**
![ss1](https://github.com/Displax/safetynet-fix/assets/16299826/b208d6d2-0fa8-4563-859b-125b9d88fb7c)
![ss2](https://github.com/Displax/safetynet-fix/assets/16299826/ddacaeae-773c-425c-a227-4073e69bb300)

**Device info**
Device model: Nexus 6P 
Android version: Android 8.1.0
ROM name/version: Stock ROM + Magisk 26.1 + magiskhide + universal fix, your mod (this repo) 

**Logs**
[issue.log](https://github.com/Displax/safetynet-fix/files/11828805/issue.log)

**Additional context**

**Checklist**
- [X] All information is present
- [X] Logs are attached
- [] I have tried installing and configuring [MagiskHide Props Config](https://github.com/Magisk-Modules-Repo/MagiskHidePropsConf)

Is this possible - how can I pass SafetyNet's Hardware Attestation or Play Integrity's `STRONG_ATTESTATION` ??

**Comment by sdfgsdfgd** [comment]
this ancient phone (Nexus 6P) - they don't even have the secure chip, so Google is literally keeping the device private keys somewhere in read only memory right ? 

shouldn't it be actually really easy to pass the strong attestation / hardware attestation with this one at least ?

**Comment by Displax** [comment]
You are definitely doing something wrong.
1. You need Magisk with Zygisk support (24.0+).
2. You need enable Zygisk in Magisk settings.
3. You need latest version of my MOD (2.4.0-1.3).
4. You **should not** install/enable/use Riru.
5. You **should not** use something third party solutions like "magiskhide".

**Comment by Displax** [comment]
> Is this possible - how can I pass SafetyNet's Hardware Attestation or Play Integrity's `STRONG_ATTESTATION` ??

**NO**. Not possible. You need stock ROM and locked bootloader for it.
